version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jt
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "5000:3306"
    volumes:
      - apiData:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  apiData:  
